url = http://localhost:5173/

username = naveenk
password = test@123

browser = FF

signup_fullname = Test User
signup_email = testuser@example.com
signup_password = test123

cart_email = xiu@test.com
cart_password = password123
